# Generated by Django 4.2.15 on 2024-10-12 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_user_token"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="token",
            field=models.CharField(
                blank=True, max_length=255, null=True, unique=True, verbose_name="Токен"
            ),
        ),
    ]
