# Generated by Django 4.2.15 on 2024-09-17 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0003_remove_product_manufactured_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="views_counter",
            field=models.PositiveBigIntegerField(
                default=0, verbose_name="Количество просмотров"
            ),
        ),
    ]
