# Generated by Django 4.2.15 on 2024-10-06 12:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0006_alter_version_options_remove_version_name_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="version",
            options={"verbose_name": "Версия", "verbose_name_plural": "Версии"},
        ),
        migrations.AlterField(
            model_name="version",
            name="is_active",
            field=models.BooleanField(verbose_name="Признак текущей версии"),
        ),
        migrations.AlterField(
            model_name="version",
            name="product",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="versions",
                to="catalog.product",
                verbose_name="Продукт",
            ),
        ),
        migrations.AlterField(
            model_name="version",
            name="version_name",
            field=models.CharField(max_length=150, verbose_name="Название версии"),
        ),
        migrations.AlterField(
            model_name="version",
            name="version_number",
            field=models.PositiveIntegerField(verbose_name="Номер версии"),
        ),
    ]
