# Generated by Django 4.2.15 on 2024-10-19 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0012_product_is_published"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="slug",
            field=models.CharField(
                blank=True, max_length=150, null=True, verbose_name="slug"
            ),
        ),
    ]
